### ISSUE TITLE
Invalid types generates errors

### ISSUE THREAD

**Issue by jens-peterolsson** [cjoudrey/graphql-schema-linter#157] opened 2018-11-29 06:07 UTC
E.g. if linting a schema with a type "string" instead of "String" in it. Should return a helpful validation error, not an unhandled js-error.

**Comment by cjoudrey** [comment] 2018-11-29 13:57
Thanks for opening this issue @jens-peterolsson.

I believe this is issue is related to #53, #154, and #136.

The root cause is that the method this library (`buildASTSchema` from `graphql-js`) uses to parse / validate / build the GraphQL schema historically did not provide the right data to make the change you are suggesting. There is an open issue in `graphql-js` to address this: https://github.com/graphql/graphql-js/issues/546. I'll keep an eye on it.

**Comment by cjoudrey** [comment] 2019-01-16 04:17
Will be fixed in next release by #163.

**Closed by cjoudrey** 2019-01-16 04:17 UTC
