### ISSUE TITLE
Failed to parse schema without `schema`

### ISSUE THREAD

**Issue by lxsli** [cjoudrey/graphql-schema-linter#177] opened 2019-04-30 09:26 UTC
```
% ~/.yarn/bin/graphql-schema-linter user-api/resources/plaza.graphqls
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

TypeError: Cannot read property '0' of undefined
    at /home/alee/.config/yarn/global/node_modules/graphql-schema-linter/lib/runner.js:76:70
    at Array.reduce (<anonymous>)
    at groupErrorsBySchemaFilePath (/home/alee/.config/yarn/global/node_modules/graphql-schema-linter/lib/runner.js:75:17)
    at run (/home/alee/.config/yarn/global/node_modules/graphql-schema-linter/lib/runner.js:67:23)
    at Object.<anonymous> (/home/alee/.config/yarn/global/node_modules/graphql-schema-linter/lib/cli.js:15:32)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Adding this fixed it:

```
schema { query: Plaza }
```

**Comment by lxsli** [comment] 2019-04-30 09:27
Oops, dup #172

**Comment by cjoudrey** [comment] 2019-11-01 00:46
Thanks for the report @lxsli. Closing because it is a dupe of #172 as you mentioned.

**Closed by cjoudrey** 2019-11-01 00:46 UTC
