### ISSUE TITLE
Self contained executable

### ISSUE THREAD

**Issue by jregistr** [cjoudrey/graphql-schema-linter#195] opened 2019-11-11 15:55 UTC
Hello!
I'm interested in using this linter as a self-contained executable. The idea is that everyone is using the exact same version, and for people to not be required to have installed node and global installed this linter. 

I've kind of managed to get this working using pkg: https://www.npmjs.com/package/pkg

Albeit, a bit hacky (I'll include some details in a follow-up comment).

Is there any interest in official support for this? As well, what are some ways this can be done(fishing for ideas)?

**Comment by jregistr** [comment] 2019-11-11 15:57
The hack I mentioned involved adding an index.js to the rules dir exporting all the rules in an array and importing them in the configuration.js. This was the only way I got pkg to include them.
```js
export const allRules = [
   ....
    require("./defined_types_are_used"),
    require("./deprecations_have_a_reason"),
   ...
]
```
```js
import { allRules } from "./rules"
// this.rulesImport = allRules;
 this.rules = null;
...

**Comment by cjoudrey** [comment] 2019-11-12 01:32
Hey @jregistr that's super interesting! 😄 I haven't put much thought in a self-contained executable for `graphql-schema-linter`. I can see the appeal though.

I never used [`pkg`](https://www.npmjs.com/package/pkg) before, but I suspect the reason you had to do that hack is because the built in rules [are dynamically loaded](https://github.com/cjoudrey/graphql-schema-linter/blob/db3f5bfc9d355d5ecbf4e8bec83bc3855bb24ab3/src/configuration.js#L143-L145).

I tried `pkg` locally and it confirmed that suspicious:

```
> Warning Cannot resolve 'rulePath'
  /Users/cjoudrey/code/cjoudrey/graphql-schema-linter/lib/configuration.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

I dug a bit into `pkg`'s `README` and saw found [this](https://github.com/zeit/pkg/blob/d271f13dc2d6f7fa71573397b9b5e396d667f726/README.md#config). I pushed a fix to `master` (https://github.com/cjoudrey/graphql-schema-linter/commit/5e787cd127f770854da948e62293c92e5a01a9f6) which should remove the need for that hack.

Before the fix you can see it wasn't picking up built-in rules:

```
$ git reset db3f5bfc9d355d5ecbf4e8bec83bc3855bb24ab3 --hard
HEAD is now at db3f5bf Drop support for node v6

$ yarn pkg -t node10-macos .
yarn run v1.13.0

$ /Users/cjoudrey/code/cjoudrey/graphql-schema-linter/node_modules/.bin/pkg -t node10-macos .
> pkg@4.4.0
> Warning Cannot resolve 'rulePath'
  /Users/cjoudrey/code/cjoudrey/graphql-schema-linter/lib/configuration.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
✨  Done in 3.27s.

$ ./graphql-schema-linter test/fixtures/schema.graphql

✔ 0 errors detected
```

With the fix this now works:

```
$ git reset --hard 5e787cd127f770854da948e62293c92e5a01a9f6
HEAD is now at 5e787cd Specify scripts dir for `pkg`

$ yarn pkg -t node10-macos .
yarn run v1.13.0

$ /Users/cjoudrey/code/cjoudrey/graphql-schema-linter/node_modules/.bin/pkg -t node10-macos .
> pkg@4.4.0
> Warning Cannot resolve 'rulePath'
  /Users/cjoudrey/code/cjoudrey/graphql-schema-linter/lib/configuration.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
✨  Done in 2.47s.

$ ./graphql-schema-linter test/fixtures/schema.graphql
/Users/cjoudrey/code/cjoudrey/graphql-schema-linter/test/fixtures/schema.graphql
1:1 The object type `Query` is missing a description.            types-have-descriptions
1:1 A `PageInfo` object type is required as per the Relay spec.  relay-page-info-spec
2:3 The field `Query.a` is missing a description.                fields-have-descriptions

✖ 3 errors detected
```

In terms of officially supporting this, do you mean providing pre-built these binaries with each release? If so, it would involve writing a script to pre-build the binaries and attaching them when I create the releases. If people want this, I don't mind doing it.

One thing that isn't really solved by this is custom rules. If people want custom rules, they'll still need to distribute them with the binary or build their own binary. I don't think it's a blocker to this, but figured I'd mention it.

**Comment by jregistr** [comment] 2019-11-12 19:51
>In terms of officially supporting this, do you mean providing pre-built binaries with each release?

Yeah, that's the idea I had in mind. However, if no one else needs this, I think your PR https://github.com/cjoudrey/graphql-schema-linter/commit/5e787cd127f770854da948e62293c92e5a01a9f6 and perhaps documentation for how someone interested can package the linter would suffice. 

And speaking of custom tests! I gave a quick run with the custom rule **LintDirective** from https://github.com/mobilcom-debitel/graphql-schema-linter-extras/blob/master/lib/lint-directive.js
and it worked. Though I did not try the others.
I'll go ahead and do some further testing with custom rules and report back here.
---
Lastly, regarding **nexe**, have you done any testing with it? I wonder if it would have the same loading concern as pkg. I had a quick look at the docs and I did not see a ref to something similar to the `scripts` config option that pkg has for dynamic load cases.

**Comment by jregistr** [comment] 2019-11-12 19:53
Btw, is the repo here: https://github.com/mobilcom-debitel/graphql-schema-linter-extras
an example of the recommended method for developing custom rules?
It's another npm project which references this one as a peer dependency.

**Comment by cjoudrey** [comment] 2020-02-29 00:55
Sorry for the delayed response. That's the first time I see that repository. You can find some other examples here: https://github.com/cjoudrey/graphql-schema-linter/tree/master/src/rules

**Comment by cjoudrey** [comment] 2020-02-29 00:56
I'm going to close this issue for now as I don't have plans on making binaries available. If there is more interest, happy to re-open it later. Thanks!

**Closed by cjoudrey** 2020-02-29 00:56 UTC
